### ISSUE TITLE
Trouble importing

### ISSUE THREAD

**Issue by DusanMilko** [d3/d3-time-format#20]
I'm having trouble importing d3-time-format.

I'm using browserify and npm and my code looks like:

```
import d3 from 'd3';
import timeFormat from 'd3-time-format';

...

var parseDate = d3.timeFormat('%b-%y'); // Error happens here
```

Later when I call d3.timeFormat it gives an error of undefined

```
Cannot read property 'timeFormat' of undefined
```

**Comment by mbostock** [comment]
Here are a couple introductions to ES2015 modules:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import
http://www.2ality.com/2014/09/es6-modules-final.html

Some problems with your code snippet:

* You’re trying to import the default export from d3, but d3 provides no default export. If you want to import everything, you need to say:

```js
import * as d3 from "d3";
```

* You’re trying to import the default export from d3-time-format, but d3-time-format provides no default export. If you want to import timeFormat, you need to say:

```js
import {timeFormat} from "d3-time-format";
```

* You’re using both d3 and d3-time-format, which is redundant because d3 re-exports everything from d3-time-format. If you are using ES2015 modules, then I recommend you use the D3 submodules directly rather than using the d3 default bundle; the latter is primarily intended for vanilla environments (although it also works in AMD and CommonJS). In particular, beware that some bundlers do not yet observe the jsnext:main defined in the package.json file, so they may require some configuration to ensure that you are importing from the ES2015 source and not the built UMD bundle.

* It looks like you’re trying to parse dates rather than format them, so you probably want to use [d3.timeParse](https://github.com/d3/d3-time-format#timeParse) rather than [d3.timeFormat](https://github.com/d3/d3-time-format#timeFormat). So you probably want something like this:

```js
import {timeParse} from "d3-time-format";
var parseDate = timeParse("%b-%y");
parseDate("Jul-16"); // Fri Jul 01 2016 00:00:00 GMT-0400 (EDT)
```

In the future, please use Stack Overflow tag d3.js or the d3-js Google group to ask for help. These issues are for feature requests and bug reports only. Thank you!
